version: '3'

services:
    rails_app:
        build: ./app/
        ports:
            - "80:80"
        depends_on:
            - db
    db:
        build: ./db/
        ports:
            - "5432:5432"
        volumes:
            - ./db/data:/var/lib/postgresql/data
        environment:                                                                                                                                                                                       
            POSTGRES_USER: db_user
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password